#!/bin/bash

cd $(dirname "$0")
mydir=$(pwd)
projectdir=$(cd .. && pwd)

RESULT=0
declare -a tests failed

# Find tests to execute
if [ $# -ne 0 ]
then
    tests=$@
else
    tests=(${mydir}/test????-*)
fi

for t in ${tests[@]}
do
    $t
    if [ $? -ne 0 ]
    then
        RESULT=1
        failed+=($t)
    fi
done

if [ ${#failed[@]} -ne 0 ]
then
    echo >&2 "Some tests failed:"
    for t in ${failed[@]}
    do
        echo >&2 $t
    done
fi

exit $RESULT
