#!/bin/bash -ex

. "$(dirname "$0")/common.sh"

branch=$(git branch --show-current)

########################################################################
# Setup
#
########################################################################

touch one && git add one
git commit -m "First commit"
git push origin ${branch}

pushd ..
git clone remote copy
pushd copy
git config obsolescence.enabled true
git config extensions.worktreeConfig true
popd && popd

########################################################################
# Create a change, amend it in a different workspace and then amend it
# again in the original workspace without pulling the other changes.
#
########################################################################
echo "fix me" > two
git add two
git commit -m "proposed code"

git push origin ${branch}

pushd ../copy
git fetch origin
git merge origin/${branch}

echo "fixed" > two
git add two
git commit --amend --no-edit
git push origin
popd

# Amend the original commit without first pulling the fix from the other
# workspace.
echo "new stuff" > three
git add three
git commit --amend --no-edit

# Using non-obsolescence aware git, this push would succeed and clobber the fix
# made in the other workspace. With obsolescence, it fails.
not git push origin ${branch}
git fetch origin ${branch}
not git push origin ${branch}

# Note that rebase here does some new magic. It notices that there are
# divergent commits from the same change on the two branches and merges them
# together. The resulting commit will have two obsoletes references showing
# that they have been merged together.
git rebase origin/${branch}
test "${branch}" = "$(git branch --show-current)"

# Since the divergent change has been resolved, we can now push the result
# back to origin.
git push origin ${branch}

# Workspace should be clean and the contents have been merged together.
test -z "$(git status --porcelain)"
test "" = "$(<one)"
test "fixed" = "$(<two)"
test "new stuff" = "$(<three)"
