#!/bin/bash -x

# Check to see if this script was run from a git repository. If not, create one
# and cd to it.
if ! git rev-parse --show-toplevel >/dev/null 2>&1
then
    echo >&2 "Run this from within a git working directory"
    exit 1
fi

mydir=$(cd $(dirname "$0") && pwd)
for hook in post-rewrite pre-push
do
    ln -sf ${mydir}/hooks/${hook} $(git rev-parse --git-dir)/hooks/${hook}
done
